services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins.controller
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yml
      - JENKINS_ADMIN_USERNAME=${JENKINS_ADMIN_USERNAME:-admin}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-admin}
      - JENKINS_AGENT_USERNAME=${JENKINS_AGENT_USERNAME:-agent}
      - JENKINS_AGENT_PASSWORD=${JENKINS_AGENT_PASSWORD:-agent}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  jenkins-agent1:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins.agent
    environment:
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
      - JENKINS_AGENT_USERNAME=${JENKINS_AGENT_USERNAME:-agent}
      - JENKINS_AGENT_PASSWORD=${JENKINS_AGENT_PASSWORD:-agent}
    depends_on:
      - jenkins

  jenkins-agent2:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins.agent
    environment:
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
      - JENKINS_AGENT_USERNAME=${JENKINS_AGENT_USERNAME:-agent}
      - JENKINS_AGENT_PASSWORD=${JENKINS_AGENT_PASSWORD:-agent}
    depends_on:
      - jenkins



