jenkins:
  mode: NORMAL
  numExecutors: 0

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USERNAME}
          password: ${JENKINS_ADMIN_PASSWORD}
        - id: ${JENKINS_AGENT_USERNAME}
          password: ${JENKINS_AGENT_PASSWORD}
  
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: admin
            permissions: 
              - Overall/Administer
            entries: 
              - user: ${JENKINS_ADMIN_USERNAME}
          - name: agent
            permissions: 
              - Overall/Read
              - Agent/Connect
              - Agent/Disconnect
              - Agent/Build
            entries: 
              - user: ${JENKINS_AGENT_USERNAME}

  nodes:
    - permanent:
        name: agent1
        launcher: inbound
        remoteFS: /home/jenkins/agent
    - permanent:
        name: agent2
        launcher: inbound
        remoteFS: /home/jenkins/agent
tool:
  nodejs:
    installations:
      - name: Node 20.x
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: 20.19.0
      - name: Node 22.x
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: 22.17.0
                - nodeJSInstaller:
                    id: 20.19.0

jobs:
  - script: |
      multibranchPipelineJob('jenkins-to-buildkite') {
          branchSources {
              github {
                  id('jenkins-to-buildkite')
                  scanCredentialsId('github-pat')
                  repoOwner('cnunciato')
                  repository('jenkins-to-buildkite')
              }
          }
          factory {
              workflowBranchProjectFactory {
                  scriptPath('app/Jenkinsfile')
              }
          }
          
          configure { node ->
              def traits = node / sources / data / 'jenkins.branch.BranchSource' / source / traits
              traits << 'org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait' {
                  strategyId(3)
              }
          }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-pat"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_TOKEN}"
              description: "${GITHUB_USERNAME}'s personal access token"

unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN_EMAIL}
    url: http://localhost:8080/

  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
