agents:
  queue: "hosted-linux"

common:
  install-node: &install-node |
    # curl -fsSL https://deb.nodesource.com/setup_{{matrix.node_version}}.x | bash
    # sudo apt install nodejs

    export NVM_DIR="\$HOME/.nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    source "\$NVM_DIR/nvm.sh"
    nvm install v{{matrix.node_version}}
    node -v && npm -v

  matrix: &matrix
    setup:
      node_version:
        - 20
        - 22

steps:

  - label: ":eslint: Lint"
    id: lint
    commands:
      - *install-node
      - |
        cd app && npm ci
        npm run lint

    

  - label: ":vitest: Test"
    id: test
    commands:
      - *install-node

    matrix: *matrix

  - label: ":wrench: Build"
    id: build   # This is optional, as nothing references it.

    depends_on: 
      - lint
      - test

    commands:
      - *install-node
    
    matrix: *matrix

    
    artifact_paths:
      - app/coverage/**/* 