agents:
  queue: "hosted-linux"
steps:
  - label: ":nodejs: Node.js {{matrix.node_version}} build"
    commands: |
      export BUILDKITE_ANALYTICS_TOKEN="$$(buildkite-agent secret get TEST_ENGINE_TEST_SUITE_JENKINS_TO_BUILDKITE)"
      
      echo "--- Install Node.js {{matrix.node_version}}"
      node -v

      # curl -fsSL https://deb.nodesource.com/setup_{{matrix.node_version}}.x | sudo -E bash -
      # sudo apt install nodejs

      # export NVM_DIR="$$HOME/.nvm"
      # curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      # source "$$NVM_DIR/nvm.sh"
      # nvm install v{{matrix.node_version}}

      export MISE_DATA_DIR="/mise"
      export MISE_CONFIG_DIR="/mise"
      export MISE_CACHE_DIR="/mise/cache"
      export MISE_INSTALL_PATH="/usr/local/bin/mise"
      export PATH="/mise/shims:$$PATH"

      curl https://mise.run | sh
      mise install --global node@{{matrix.node_version}}
      node -v
      
      cd app
      npm ci
      npm run lint
      npm run test
      npm run build
      
    matrix:
      setup:
        node_version:
          - 20
          - 22
    
    artifact_paths:
      - app/coverage/**/* 