agents:
  queue: "hosted-linux"

common:
  install: &install |
    curl -fsSL https://deb.nodesource.com/setup_{{matrix.node_version}}.x | bash
    sudo apt install nodejs
    cd app && npm ci
  matrix: &matrix
    setup:
      node_version:
        - 20
        - 22

steps:
  - id: lint
    label: ":eslint: Lint"
    matrix: *matrix
    commands:
      - *install
      - npm run lint

  - id: test
    label: ":vitest: Test"
    matrix: *matrix
    commands:
      - *install
      - npm test

  - id: build
    label: ":wrench: Build"
    matrix: *matrix
    commands:
      - *install
      - npm run build
    depends_on: 
      - lint
      - test

    artifact_paths:
      - app/coverage/**/* 