agents:
  queue: "hosted-linux"
steps:
  - label: ":nodejs: Node.js {{matrix.node_version}} build"
    commands: |
      export BUILDKITE_ANALYTICS_TOKEN="$$(buildkite-agent secret get TEST_ENGINE_TEST_SUITE_JENKINS_TO_BUILDKITE)"
      
      echo "--- Install Mise and Node {{matrix.node_version}}"
      curl https://mise.run | sh
      export PATH="$$HOME/.local/bin:$PATH"
      mise install node@{{matrix.node_version}}
      mise use --global node@{{matrix.node_version}}
      mise bin-paths
      which node
      node -v
      npm -v

      cd app
      npm ci
      npm run lint
      npm run test
      npm run build
      
    matrix:
      setup:
        node_version:
          - 20
          - 22
    
    artifact_paths:
      - app/coverage/**/* 