agents:
  queue: "hosted-linux"
steps:
  - label: ":nodejs: Node.js {{matrix.node_version}} build"
    commands: |

      # Install Node.js
      # Do some stuff....

      cd app
      npm ci
      npm run lint
      npm run test:unit
      npm run build
    matrix:
      setup:
        node_version:
          - 20.x
          - 22.x
    
    artifact_paths:
      - app/coverage/**/*